# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# enable facebook comment
facebook-comment: true 

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Về tôi',   url: 'about.html'}
- {name: 'Nhà kho', url: 'writing.html'}
- {name: 'Gọi cho tôi', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook',   link: 'https://www.facebook.com/remiblog'}
- {icon: 'twitter',    link: 'https://twitter.com/fb'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/fb/'}
- {icon: 'envelope',   link: 'mailto:l.nguyen@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Chia sẻ bài viết!'

related_posts: 'Bài viết khác của tôi:'

post_date_prefix: 'Written on'
